name: Update docs

on:
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          ref: "gh-pages"
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          path: "docs"

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: |
          npm install -g @microsoft/api-extractor

          # https://github.com/microsoft/rushstack/issues/4586
          npm install -g @microsoft/api-documenter@7.23.38

      - name: Re-generate docs
        run: |
          MAJOR_VERSION=v$(node -p "require('./package.json').version.split('.')[0]")
          DOCS_OUTPUT_FOLDER=${GITHUB_WORKSPACE}/docs/${MAJOR_VERSION}

          mkdir -p ./etc
          mkdir -p $DOCS_OUTPUT_FOLDER

          npm ci
          npm run api:extract
          DOCS_OUTPUT_FOLDER=$DOCS_OUTPUT_FOLDER npm run api:document

          cd ${GITHUB_WORKSPACE}/docs
          git commit -am "Re-generated docs."
          git push
